<a href="https://colab.research.google.com/github/kouliki/celebal_task5/blob/main/Celebal_Task5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/titanic.csv')

# Data Preprocessing

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [6]:
cols = ['Name', 'Ticket', 'Cabin']
df = df.drop(cols, axis=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Fare         891 non-null    float64
 8   Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 62.8+ KB

In [9]:
df.isna()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False
887,False,False,False,False,False,False,False,False,False
888,False,False,False,False,True,False,False,False,False
889,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False

In [10]:
df = df.dropna()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Sex          712 non-null    object
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object
dtypes: float64(2), int64(5), object(2)
memory usage: 55.6+ KB

# Missing values

In [12]:
dummies=[]
cols=['Pclass', 'Sex', 'Embarked']
for col in cols:
  dummies.append(pd.get_dummies(df[col]))

In [15]:
titanic_dummies = pd.concat(dummies, axis=1)

In [16]:
df = pd.concat((df,titanic_dummies), axis=1)

In [17]:
df['Age'] = df['Age'].interpolate()

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 712 entries, 0 to 890
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  712 non-null    int64
 1   Survived     712 non-null    int64
 2   Pclass       712 non-null    int64
 3   Sex          712 non-null    object
 4   Age          712 non-null    float64
 5   SibSp        712 non-null    int64
 6   Parch        712 non-null    int64
 7   Fare         712 non-null    float64
 8   Embarked     712 non-null    object
 9   1            712 non-null    bool
 10  2            712 non-null    bool
 11  3            712 non-null    bool
 12  female       712 non-null    bool
 13  male         712 non-null    bool
 14  C            712 non-null    bool
 15  Q            712 non-null    bool
 16  S            712 non-null    bool
dtypes: bool(8), float64(2), int64(5), object(2)
memory usage: 61.2+ KB

In [28]:
df.drop_duplicates(inplace=True)

# Normalization

In [21]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])

In [22]:
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,1,2,3,female,male,C,Q,S
0,1,0,3,male,-0.527669,1,0,-0.516380,S,False,False,True,False,True,False,False,True
1,2,1,1,female,0.577094,1,0,0.694046,C,True,False,False,True,False,True,False,False
2,3,1,3,female,-0.251478,0,0,-0.503620,S,False,False,True,True,False,False,False,True
3,4,1,1,female,0.369951,1,0,0.350326,S,True,False,False,True,False,False,False,True
4,5,0,3,male,0.369951,0,0,-0.501257,S,False,False,True,False,True,False,False,True

# Encoding

In [24]:
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [25]:
df.head()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,1,2,3,female,male,C,Q,S,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,-0.527669,1,0,-0.516380,False,False,True,False,True,False,False,True,True,False,True
1,2,1,1,0.577094,1,0,0.694046,True,False,False,True,False,True,False,False,False,False,False
2,3,1,3,-0.251478,0,0,-0.503620,False,False,True,True,False,False,False,True,False,False,True
3,4,1,1,0.369951,1,0,0.350326,True,False,False,True,False,False,False,True,False,False,True
4,5,0,3,0.369951,0,0,-0.501257,False,False,True,False,True,False,False,True,True,False,True

# Feature Engineering

In [26]:
df['fsmilySize']=df['SibSp'] + df['Parch'] + 1

In [27]:
df

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,1,2,3,female,male,C,Q,S,Sex_male,Embarked_Q,Embarked_S,fsmilySize
0,1,0,3,-0.527669,1,0,-0.516380,False,False,True,False,True,False,False,True,True,False,True,2
1,2,1,1,0.577094,1,0,0.694046,True,False,False,True,False,True,False,False,False,False,False,2
2,3,1,3,-0.251478,0,0,-0.503620,False,False,True,True,False,False,False,True,False,False,True,1
3,4,1,1,0.369951,1,0,0.350326,True,False,False,True,False,False,False,True,False,False,True,2
4,5,0,3,0.369951,0,0,-0.501257,False,False,True,False,True,False,False,True,True,False,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,886,0,3,0.646142,0,5,-0.102875,False,False,True,True,False,False,True,False,False,True,False,6
886,887,0,2,-0.182430,0,0,-0.407687,False,True,False,False,True,False,False,True,True,False,True,1
887,888,1,1,-0.734812,0,0,-0.086335,True,False,False,True,False,False,False,True,False,False,True,1
889,890,1,1,-0.251478,0,0,-0.086335,True,False,False,False,True,True,False,False,True,False,False,1
890,891,0,3,0.162808,0,0,-0.506928,False,False,True,False,True,False,True,False,True,True,False,1